from .about_moscow_page import AboutMoscowPage
from .investment_map_page import InvestmentMapPage
from .main_page import MainPage
from .moscow_in_numbers_page import MoscowInNumberPage
from .online_services_page import OnlineServicesPage
from .podpiska_inwest_digest_page import PodpiskaInwestDigestPage
from .projects_page import ProjectsPage
from .tenders_page import TendersPage
from .new_tenders_page import NewTendersPage